### ISSUE TITLE
Call after using hljs.highlightBlock

### ISSUE THREAD

**Issue by jonathanwiesel** [TRSasasusu/highlightjs-highlight-lines.js#1]
Hi there, great plugin you have here.

I noticed that when using the `hljs.highlightBlock` syntax and after calling `hljs.initHighlightLinesOnLoad` it doesn't seem to work. I see no information regarding usage for `hljs.highlightBlock` in the repo or if its supported

**Comment by TRSasasusu** [comment]
Thank you for making this issue.
I made a [DEMO](https://trsasasusu.github.io/highlightjs-highlight-lines.js/use-highlight-block.html) to use `hljs.highlightBlock` with highlighting lines.

Also, please use `v1.1.6` (or more).
