### ISSUE TITLE
First Line number

### ISSUE THREAD

**Issue by HowToSolutions** [TRSasasusu/highlightjs-highlight-lines.js#2]
Hi, I just discovered your plugin and its working great.

But, shouldn't the first line start with number 1 and not 0?

When highlighting the first line, I expected to set _start: 1_, but you have to set it to _start: 0_ instead.

**Comment by TRSasasusu** [comment]
Thank you for raising this issue!

Now, I released `v1.2.0`. Here, I introduced `highlightLinesAll`, where the first line starts with number *1*.  
So, please use this new API.

(`initHighlightLinesOnLoad` is deprecated)
